# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e43a0c3c352888a7c3beda5f08517ab630e8785690ce41fd97477757efad371581033800a58729f1d8d1a005ca7eb8f905ab4adf1aa562bbd2e7bbd36213bf1

test:
  secret_key_base: db8c0df0d76d66033b82f995f6b34ff7d3a3c4d67f63526cf47e572206183f78df472c1378a94261310ed0f6bd014c595934d5204f71a00c8ee834f5ad29e12a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
